name: Node Build
on:
  push:
    branches: [t2]
  pull_request:

jobs:
  build:
    runs-on: orangepiplus5-docker   # 必须匹配你 Runner 的标签
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        cache: 'npm'

        #with:
         # node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/